### PR TITLE
refactor: use to_digit instead of custom HEX_MAP

### PR DESCRIPTION
**Pull request by lukaslihotzki**

### CODE REVIEW

**Comment by mdecimus** [comment]
Have you benchmarked `to_digit` against HEX_MAP? Last time I did this benchmark using HEX_MAP was slightly faster.

**Comment by lukaslihotzki** [comment]
This is difficult to compare, because HEX_MAP is more memory-intensive, and the standard to_digit implementation is more arithmetic and branch-intensive. What's faster depends on the hardware, the remaining code of the xtest function (pipeline), and other SMTP parsing (affects caching), and how often hex escapes are used (also due to caching). Therefore, benchmarks should not test the hex digit conversion directly, but the complete SMTP parsing of inputs similar to real inputs. It would certainly be helpful to have a `cargo bench` for that, but I don't think there will be a measurable difference between HEX_MAP and to_digit at this point, so I would propose to choose the simpler code.

Also, the existing code uses `is_ascii_hexdigit` *additionally*, which does most of the arithmetic and branching needed for `to_digit`. So, are you sure that the current `is_ascii_hexdigit`-and-`HEX_MAP`-combination is faster than just `to_digit` on any system? That would be really surprising.

**Comment by lukaslihotzki** [comment]
Looking at the assembler output, it seems like `char::from(num).to_digit(16).is_some()` is even faster than `num.is_ascii_hexdigit()`, because `to_digit` uses a [bitwise operation](https://doc.rust-lang.org/src/core/char/methods.rs.html#353) for ASCII case conversion. So, switch to that and start using the result.

**Comment by mdecimus** [comment]
Great, merged!

**Pull request merged**
